spring:
  application:
    name: lanchinho
  datasource:
    username: postgres
    password: VFCvfc
    url: jdbc:postgresql://localhost:5432/lanchinho
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create
server:
  port: 8080
